### ISSUE TITLE
Last Trade column no available 

### ISSUE THREAD

**Issue by waveriderai** [tke578/barchart#4]
Recently barchart added the 'delta' column to the end, and somehow the 'last trade' column is dropped out. The 'last trade' column is still available on the website. Is there a way to add the 'last trade' column back?

**Comment by tke578** [comment]
This will be up soon @gsu421 https://github.com/tke578/barchart/pull/6

**Comment by tke578** [comment]
closed via https://github.com/tke578/barchart/pull/6
