### ISSUE TITLE
ParsingError: Index error on table headers, check response

### ISSUE THREAD

**Issue by waveriderai** [tke578/barchart#5]
Received the following error message for the past week consistently. Any thoughts?

    raise ParsingError(msg='Index error on table headers, check response')
barchart.helpers.errors.ParsingError: Parsing error: Index error on table headers, check response

**Comment by Meciah** [comment]
Receiving the same error as above. Been looking into a solution but no luck so far.

**Comment by waveriderai** [comment]
I suspect the problem is related to the recent new column [Delta] added on the barcahrt website. In the directory barchart/helpers/parser.py 

perhaps need to change the value from 15 to 16 (line 17, 19, 29). Not sure if there are other places that needs change. It will be great if someone can help looking into the additional column added in the header.

**Comment by tke578** [comment]
Hey everyone! Sorry for the late response. Work has been busy these past few weeks. 
Thank for discovering the parsing issue. Also found out the scraper is being blocked by barchart's server intermittently via Amazon Cloudfront

 ```The request could not be satisfied```

I'm going to try to figure out a solution to not being blocked.
Suggestions welcomed!

**Comment by tke578** [comment]
WIP on https://github.com/tke578/barchart/pull/6 
Will be merged soon

**Comment by tke578** [comment]
closed via https://github.com/tke578/barchart/pull/6

**Comment by waveriderai** [comment]
awesome. thank you
